//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminUsers
    {
        public int AdminID { get; set; }
        [Required(ErrorMessage = "账户名不可以为空")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "密码不可以为空")]
        public string Pwd { get; set; }
        public int Role { get; set; }
    }
}
